Feature/divider
nuxeric/cpsc304project pull request #9
Opened 2020-11-18 18:22 UTC by ShaunDonn

Creates a button in dashboard called "Divide Personnel" that, when pressed, displays a table of the Personnel who work in all warehouses. I don't love the way it flows or the fact that the button is called "Divide Personnel", but for the sake of meeting the rubric requirements, it's enough for now. Would like to add the button to the Personnel page if there's time.

Created a new class, the same as accounts/personnel, but it only includes the Personnel id, first_name, and last_name. 

personnel_divided.ts has a method called listDividedPersonnel, which returns the result of the division query. This method is called in dividerRoute, which gives it the name "div_result". This variable is then used to fill in the table body in divider.ejs.

I know the naming isn't very straight forward, so if you guys have any suggestions for changes to names of any classes, variables, etc. let me know.

2020-11-18 18:29 UTC, pseigo requested changes
Minor changes, otherwise looks good!

2020-11-18 18:29 UTC, pseigo commented on web/src/model/division/personnel_divided.ts
> +export default class DividedPersonnel {
DividedPersonnel or PersonnelDivided?

2020-11-18 18:29 UTC, pseigo commented on web/src/model/division_personnel.ts
> +          return new DividedPersonnel(p.id, p.first_name, p.last_name);
You should be able to re-use the Personnel class, no? This seems like duplication to me

2020-11-18 18:29 UTC, pseigo commented on web/src/routes/divider/dividerRoute.ts
> +                res.render('web/page/divider/divider.ejs', {title: "Divided Personnel", div_result: div_result});
Would probably want to rename that template to `index.ejs` for consistency :)

2020-11-18 19:49 UTC, pseigo approved these changes

2020-11-18 19:51 UTC, pseigo commented
Ready to merge! (make sure to reinit your DB after this gets merged @nuxeric )

2020-11-18 19:57 UTC, pseigo commented
Just making it easy for Adi to check off the boxes :)

![image](https://user-images.githubusercontent.com/3186109/99581105-87ce9880-299d-11eb-854d-fbabd39bb42c.png)
![image](https://user-images.githubusercontent.com/3186109/99581133-93ba5a80-299d-11eb-8110-308935809a11.png)

2020-11-18 20:11 UTC, pseigo commented on sql_script/initialize_db.sql
> +DROP TABLE categorizes CASCADE;
This is the only change here, other lines are just whitespace changes :P

2020-11-19 01:27 UTC, ShaunDonn commented
Nice changes. Thanks @pseigo!

2020-11-19 09:37 UTC, nuxeric approved these changes

2020-11-19 09:38 UTC, merged